const data = {
  "PO Stock": {
    idpostock: "98",
    postockcode: "3JQ65YLW",
    postockcreate: "2024-09-09 08:36:50",
    idapiauth: "21",
    idoutlet: "16",
    username: "prettyzahrani2003@gmail.com",
    outletname: "E DENTAL - DOKTER GIGI LAMPUNG",
    statusstock: "0",
    status: "0",
  },
  "Detail PO": [
    {
      idpostockdetail: "354",
      idpostock: "98",
      idstock: "51",
      sku: "AL7",
      itemname: "CHEEK RETRAKTOR L.M.S",
      qty: "1",
      note: "yg karet",
      statusitem: "0",
      postockcode: "3JQ65YLW",
      postockcreate: "2024-09-09 08:36:50",
      idapiauth: "21",
      idoutlet: "16",
      username: "prettyzahrani2003@gmail.com",
      outletname: "E DENTAL - DOKTER GIGI LAMPUNG",
      statusstock: "0",
      status: "0",
    },
    {
      idpostockdetail: "355",
      idpostock: "98",
      idstock: "198",
      sku: "BP67",
      itemname: "ARTICULATING PAPER",
      qty: "1",
      note: "",
      statusitem: "0",
      postockcode: "3JQ65YLW",
      postockcreate: "2024-09-09 08:36:50",
      idapiauth: "21",
      idoutlet: "16",
      username: "prettyzahrani2003@gmail.com",
      outletname: "E DENTAL - DOKTER GIGI LAMPUNG",
      statusstock: "0",
      status: "0",
    },
  ],
};
